create table COMMON_MENU
(
    MENU_CODE            VARCHAR2(100)        not null
        constraint COMMON_MENU_PK
            primary key,
    MENU_NAME            VARCHAR2(100)        not null,
    MENU_NUMBER          VARCHAR2(3)          not null,
    MENU_LEVEL           VARCHAR2(1)          not null,
    TOP_MENU_CODE        VARCHAR2(100),
    URL                  VARCHAR2(1000)       not null,
    USE_YN               CHAR                 not null,
    SYSTEM_CREATE_DATE   DATE default SYSDATE not null,
    SYSTEM_CREATE_USERID VARCHAR2(32)         not null,
    SYSTEM_UPDATE_DATE   DATE,
    SYSTEM_UPDATE_USERID VARCHAR2(32),
    MENU_SEQUENCE        NUMBER
)
/

comment on table COMMON_MENU is '메뉴관리'
/

comment on column COMMON_MENU.MENU_CODE is '메뉴코드'
/

comment on column COMMON_MENU.MENU_NAME is '메뉴명'
/

comment on column COMMON_MENU.MENU_NUMBER is '메뉴순서'
/

comment on column COMMON_MENU.MENU_LEVEL is '메뉴레벨'
/

comment on column COMMON_MENU.TOP_MENU_CODE is '상위 메뉴코드'
/

comment on column COMMON_MENU.URL is 'URL'
/

comment on column COMMON_MENU.USE_YN is '사용여부'
/

comment on column COMMON_MENU.SYSTEM_CREATE_DATE is '작성일자'
/

comment on column COMMON_MENU.SYSTEM_CREATE_USERID is '작성자ID'
/

comment on column COMMON_MENU.SYSTEM_UPDATE_DATE is '수정일자'
/

comment on column COMMON_MENU.SYSTEM_UPDATE_USERID is '수정자ID'
/

comment on column COMMON_MENU.MENU_SEQUENCE is '메뉴노출순서'
/

INSERT INTO COMMON_MENU (MENU_CODE, MENU_NAME, MENU_NUMBER, MENU_LEVEL, TOP_MENU_CODE, URL, USE_YN, SYSTEM_CREATE_DATE, SYSTEM_CREATE_USERID, SYSTEM_UPDATE_DATE, SYSTEM_UPDATE_USERID, MENU_SEQUENCE) VALUES ('SETTINGS', '설정/관리', '0', '0', '-', '#', '1', TIMESTAMP '2024-11-06 17:50:16', 'go66go66@giens.co.kr', null, null, null);
INSERT INTO COMMON_MENU (MENU_CODE, MENU_NAME, MENU_NUMBER, MENU_LEVEL, TOP_MENU_CODE, URL, USE_YN, SYSTEM_CREATE_DATE, SYSTEM_CREATE_USERID, SYSTEM_UPDATE_DATE, SYSTEM_UPDATE_USERID, MENU_SEQUENCE) VALUES ('GROUP_MANAGEMENT', '그룹관리', '0', '1', 'SETTINGS', '#', '1', TIMESTAMP '2024-11-08 14:47:02', 'go66go66@giens.co.kr', null, null, null);
INSERT INTO COMMON_MENU (MENU_CODE, MENU_NAME, MENU_NUMBER, MENU_LEVEL, TOP_MENU_CODE, URL, USE_YN, SYSTEM_CREATE_DATE, SYSTEM_CREATE_USERID, SYSTEM_UPDATE_DATE, SYSTEM_UPDATE_USERID, MENU_SEQUENCE) VALUES ('USER_MANAGEMENT', '사용자관리', '0', '1', 'SETTINGS', '#', '1', TIMESTAMP '2024-11-06 17:46:55', 'go66go66@giens.co.kr', null, null, null);
INSERT INTO COMMON_MENU (MENU_CODE, MENU_NAME, MENU_NUMBER, MENU_LEVEL, TOP_MENU_CODE, URL, USE_YN, SYSTEM_CREATE_DATE, SYSTEM_CREATE_USERID, SYSTEM_UPDATE_DATE, SYSTEM_UPDATE_USERID, MENU_SEQUENCE) VALUES ('CODE_MANAGEMENT', '코드관리', '1', '1', 'SETTINGS', '#', '1', TIMESTAMP '2024-11-06 17:50:16', 'go66go66@giens.co.kr', null, null, null);
INSERT INTO COMMON_MENU (MENU_CODE, MENU_NAME, MENU_NUMBER, MENU_LEVEL, TOP_MENU_CODE, URL, USE_YN, SYSTEM_CREATE_DATE, SYSTEM_CREATE_USERID, SYSTEM_UPDATE_DATE, SYSTEM_UPDATE_USERID, MENU_SEQUENCE) VALUES ('MENU_MANAGEMENT', '메뉴관리', '2', '1', 'SETTINGS', '#', '1', TIMESTAMP '2024-11-06 17:46:55', 'go66go66@giens.co.kr', null, null, null);
INSERT INTO COMMON_MENU (MENU_CODE, MENU_NAME, MENU_NUMBER, MENU_LEVEL, TOP_MENU_CODE, URL, USE_YN, SYSTEM_CREATE_DATE, SYSTEM_CREATE_USERID, SYSTEM_UPDATE_DATE, SYSTEM_UPDATE_USERID, MENU_SEQUENCE) VALUES ('SITE_SETTING', '사이트관리', '3', '1', 'SETTINGS', '#', '1', TIMESTAMP '2025-02-03 14:12:14', 'go66go66@giens.co.kr', null, null, null);

INSERT INTO COMMON_MENU (MENU_CODE, MENU_NAME, MENU_NUMBER, MENU_LEVEL, TOP_MENU_CODE, URL, USE_YN, SYSTEM_CREATE_DATE, SYSTEM_CREATE_USERID, SYSTEM_UPDATE_DATE, SYSTEM_UPDATE_USERID, MENU_SEQUENCE) VALUES ('GROUP_SETTING', '그룹설정', '0', '2', 'GROUP_MANAGEMENT', '/common/group/commonGroupList', '1', TIMESTAMP '2024-11-08 14:48:20', 'go66go66@giens.co.kr', null, null, null);
INSERT INTO COMMON_MENU (MENU_CODE, MENU_NAME, MENU_NUMBER, MENU_LEVEL, TOP_MENU_CODE, URL, USE_YN, SYSTEM_CREATE_DATE, SYSTEM_CREATE_USERID, SYSTEM_UPDATE_DATE, SYSTEM_UPDATE_USERID, MENU_SEQUENCE) VALUES ('USER_SETTING', '사용자설정', '1', '2', 'USER_MANAGEMENT', '/common/usersetting/userSetting', '1', TIMESTAMP '2024-11-06 17:50:16', 'go66go66@giens.co.kr', null, null, null);
INSERT INTO COMMON_MENU (MENU_CODE, MENU_NAME, MENU_NUMBER, MENU_LEVEL, TOP_MENU_CODE, URL, USE_YN, SYSTEM_CREATE_DATE, SYSTEM_CREATE_USERID, SYSTEM_UPDATE_DATE, SYSTEM_UPDATE_USERID, MENU_SEQUENCE) VALUES ('CODE_SETTING', '공통코드설정', '0', '2', 'CODE_MANAGEMENT', '/common/codeSetting', '1', TIMESTAMP '2024-11-06 17:50:16', 'go66go66@giens.co.kr', null, null, null);
INSERT INTO COMMON_MENU (MENU_CODE, MENU_NAME, MENU_NUMBER, MENU_LEVEL, TOP_MENU_CODE, URL, USE_YN, SYSTEM_CREATE_DATE, SYSTEM_CREATE_USERID, SYSTEM_UPDATE_DATE, SYSTEM_UPDATE_USERID, MENU_SEQUENCE) VALUES ('MENU_SETTING', '메뉴설정', '0', '2', 'MENU_MANAGEMENT', '/common/menuSetting', '1', TIMESTAMP '2024-11-06 17:50:16', 'go66go66@giens.co.kr', null, null, null);
INSERT INTO COMMON_MENU (MENU_CODE, MENU_NAME, MENU_NUMBER, MENU_LEVEL, TOP_MENU_CODE, URL, USE_YN, SYSTEM_CREATE_DATE, SYSTEM_CREATE_USERID, SYSTEM_UPDATE_DATE, SYSTEM_UPDATE_USERID, MENU_SEQUENCE) VALUES ('SITE_CONFIG_LIST', '사이트 설정코드 관리', '0', '2', 'SITE_SETTING', '/common/site/siteConfigList', '1', TIMESTAMP '2025-02-03 14:14:14', 'go66go66@giens.co.kr', null, null, null);

INSERT INTO COMMON_MENU (MENU_CODE, MENU_NAME, MENU_NUMBER, MENU_LEVEL, TOP_MENU_CODE, URL, USE_YN, SYSTEM_CREATE_DATE, SYSTEM_CREATE_USERID, SYSTEM_UPDATE_DATE, SYSTEM_UPDATE_USERID, MENU_SEQUENCE) VALUES ('SITE_BANNER_IMAGE_LIST', '사이트 배너이미지 관리', '1', '2', 'SITE_SETTING', '/common/site/siteBannerImageList', '1', TIMESTAMP '2025-02-03 14:13:18', 'go66go66@giens.co.kr', null, null, null);
INSERT INTO COMMON_MENU (MENU_CODE, MENU_NAME, MENU_NUMBER, MENU_LEVEL, TOP_MENU_CODE, URL, USE_YN, SYSTEM_CREATE_DATE, SYSTEM_CREATE_USERID, SYSTEM_UPDATE_DATE, SYSTEM_UPDATE_USERID, MENU_SEQUENCE) VALUES ('SITE_POPUP_NOTICE_LIST', '사이트 팝업공지 관리', '2', '2', 'SITE_SETTING', '/common/site/sitePopupNoticeList', '1', TIMESTAMP '2025-02-05 14:58:46', 'go66go66@giens.co.kr', null, null, null);
INSERT INTO COMMON_MENU (MENU_CODE, MENU_NAME, MENU_NUMBER, MENU_LEVEL, TOP_MENU_CODE, URL, USE_YN, SYSTEM_CREATE_DATE, SYSTEM_CREATE_USERID, SYSTEM_UPDATE_DATE, SYSTEM_UPDATE_USERID, MENU_SEQUENCE) VALUES ('SITE_SCHEDULED_MAIL_LIST', '사이트 메일 관리', '3', '2', 'SITE_SETTING', '/common/site/siteScheduledMailList', '1', TIMESTAMP '2025-02-18 17:29:39', 'go66go66@giens.co.kr', null, null, null);
INSERT INTO COMMON_MENU (MENU_CODE, MENU_NAME, MENU_NUMBER, MENU_LEVEL, TOP_MENU_CODE, URL, USE_YN, SYSTEM_CREATE_DATE, SYSTEM_CREATE_USERID, SYSTEM_UPDATE_DATE, SYSTEM_UPDATE_USERID, MENU_SEQUENCE) VALUES ('SITE_SENT_MAIL_MANAGEMENT_LIST', '사이트 메일 발송 현황', '4', '2', 'SITE_SETTING', '/common/site/siteSentMailManagementList', '1', TIMESTAMP '2025-02-18 17:31:28', 'go66go66@giens.co.kr', null, null, null);
