create table SITE_CONFIG
(
    CONFIG_GROUP_ID      VARCHAR2(100)  not null,
    CONFIG_KEY           VARCHAR2(500)  not null
        primary key,
    CONFIG_VALUE         VARCHAR2(100)  not null,
    DESCRIPTION          VARCHAR2(500),
    USE_YN               CHAR default 0 not null,
    SYSTEM_CREATE_DATE   DATE,
    SYSTEM_CREATE_USERID VARCHAR2(32),
    SYSTEM_UPDATE_DATE   DATE,
    SYSTEM_UPDATE_USERID VARCHAR2(32)
)
/

comment on column SITE_CONFIG.CONFIG_GROUP_ID is '설정그룹ID'
/

comment on column SITE_CONFIG.CONFIG_KEY is '설정 키'
/

comment on column SITE_CONFIG.CONFIG_VALUE is '설정 값'
/

comment on column SITE_CONFIG.DESCRIPTION is '설명'
/

comment on column SITE_CONFIG.USE_YN is '사용여부'
/

comment on column SITE_CONFIG.SYSTEM_CREATE_DATE is '작성일자'
/

comment on column SITE_CONFIG.SYSTEM_CREATE_USERID is '작성자ID'
/

comment on column SITE_CONFIG.SYSTEM_UPDATE_DATE is '수정일자'
/

comment on column SITE_CONFIG.SYSTEM_UPDATE_USERID is '수정자ID'
/

INSERT INTO SITE_CONFIG (CONFIG_GROUP_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, USE_YN, SYSTEM_CREATE_DATE, SYSTEM_CREATE_USERID, SYSTEM_UPDATE_DATE, SYSTEM_UPDATE_USERID) VALUES ('BANNER', 'BANNER_AUTO_ROTATE_YN', '1', '배너 자동넘김 여부', '1', TIMESTAMP '2025-02-14 17:31:42', 'joo717@giens.co.kr', TIMESTAMP '2025-02-14 17:31:42', 'joo717@giens.co.kr');
INSERT INTO SITE_CONFIG (CONFIG_GROUP_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, USE_YN, SYSTEM_CREATE_DATE, SYSTEM_CREATE_USERID, SYSTEM_UPDATE_DATE, SYSTEM_UPDATE_USERID) VALUES ('BANNER', 'BANNER_ROTATE_INTERVAL_SEC', '3', '배너 넘김 시간 (초)', '1', TIMESTAMP '2025-02-14 17:31:49', 'joo717@giens.co.kr', TIMESTAMP '2025-02-14 17:31:49', 'joo717@giens.co.kr');
INSERT INTO SITE_CONFIG (CONFIG_GROUP_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, USE_YN, SYSTEM_CREATE_DATE, SYSTEM_CREATE_USERID, SYSTEM_UPDATE_DATE, SYSTEM_UPDATE_USERID) VALUES ('SYSTEM_SETTINGS', 'MAINTENANCE_MODE', '0', '시스템 점검 모드', '1', TIMESTAMP '2025-02-14 09:57:51', null, TIMESTAMP '2025-02-17 11:03:16', 'joo717@giens.co.kr');
INSERT INTO SITE_CONFIG (CONFIG_GROUP_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, USE_YN, SYSTEM_CREATE_DATE, SYSTEM_CREATE_USERID, SYSTEM_UPDATE_DATE, SYSTEM_UPDATE_USERID) VALUES ('UPLOAD_SETTINGS', 'MAX_UPLOAD_SIZE_MB', '50', '최대 업로드 파일 크기 (MB)', '1', TIMESTAMP '2025-02-14 09:58:07', null, null, null);
INSERT INTO SITE_CONFIG (CONFIG_GROUP_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, USE_YN, SYSTEM_CREATE_DATE, SYSTEM_CREATE_USERID, SYSTEM_UPDATE_DATE, SYSTEM_UPDATE_USERID) VALUES ('UPLOAD_SETTINGS', 'ALLOWED_FILE_EXTENSIONS', 'jpg,png,pdf,docx', '허용된 파일 확장자', '1', TIMESTAMP '2025-02-14 09:58:07', null, TIMESTAMP '2025-02-17 14:44:08', 'joo717@giens.co.kr');
INSERT INTO SITE_CONFIG (CONFIG_GROUP_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, USE_YN, SYSTEM_CREATE_DATE, SYSTEM_CREATE_USERID, SYSTEM_UPDATE_DATE, SYSTEM_UPDATE_USERID) VALUES ('WEB_SETTINGS', 'SITE_TITLE', 'VIMS', '웹사이트 타이틀', '1', TIMESTAMP '2025-02-14 10:00:58', null, null, null);
INSERT INTO SITE_CONFIG (CONFIG_GROUP_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, USE_YN, SYSTEM_CREATE_DATE, SYSTEM_CREATE_USERID, SYSTEM_UPDATE_DATE, SYSTEM_UPDATE_USERID) VALUES ('WEB_SETTINGS', 'SITE_DESCRIPTION', '자동차 통합 관리 시스템', '웹사이트 설명 (메타 태그)', '1', TIMESTAMP '2025-02-14 10:00:58', null, TIMESTAMP '2025-02-17 11:03:52', 'joo717@giens.co.kr');
INSERT INTO SITE_CONFIG (CONFIG_GROUP_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, USE_YN, SYSTEM_CREATE_DATE, SYSTEM_CREATE_USERID, SYSTEM_UPDATE_DATE, SYSTEM_UPDATE_USERID) VALUES ('WEB_SETTINGS', 'FAVICON_URL', '/assets/favicon.ico', '파비콘 아이콘 경로', '1', TIMESTAMP '2025-02-14 10:00:58', null, null, null);
INSERT INTO SITE_CONFIG (CONFIG_GROUP_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, USE_YN, SYSTEM_CREATE_DATE, SYSTEM_CREATE_USERID, SYSTEM_UPDATE_DATE, SYSTEM_UPDATE_USERID) VALUES ('WEB_SETTINGS', 'LOGO_URL', '/assets/logo.png', '웹사이트 로고 이미지 경로', '1', TIMESTAMP '2025-02-14 10:00:59', null, null, null);
INSERT INTO SITE_CONFIG (CONFIG_GROUP_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, USE_YN, SYSTEM_CREATE_DATE, SYSTEM_CREATE_USERID, SYSTEM_UPDATE_DATE, SYSTEM_UPDATE_USERID) VALUES ('WEB_SETTINGS', 'DEFAULT_LANGUAGE', 'ko', '웹사이트 기본 언어', '1', TIMESTAMP '2025-02-14 10:00:59', null, null, null);
INSERT INTO SITE_CONFIG (CONFIG_GROUP_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, USE_YN, SYSTEM_CREATE_DATE, SYSTEM_CREATE_USERID, SYSTEM_UPDATE_DATE, SYSTEM_UPDATE_USERID) VALUES ('WEB_SETTINGS', 'ENABLE_DARK_MODE', '0', '다크 모드 기본 설정', '1', TIMESTAMP '2025-02-14 10:00:59', null, null, null);
INSERT INTO SITE_CONFIG (CONFIG_GROUP_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, USE_YN, SYSTEM_CREATE_DATE, SYSTEM_CREATE_USERID, SYSTEM_UPDATE_DATE, SYSTEM_UPDATE_USERID) VALUES ('PASSWORD_POLICY', 'MIN_LENGTH', '4', '최소 비밀번호 길이', '1', TIMESTAMP '2025-02-14 09:56:25', null, TIMESTAMP '2025-02-19 15:41:23', 'joo717@giens.co.kr');
INSERT INTO SITE_CONFIG (CONFIG_GROUP_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, USE_YN, SYSTEM_CREATE_DATE, SYSTEM_CREATE_USERID, SYSTEM_UPDATE_DATE, SYSTEM_UPDATE_USERID) VALUES ('PASSWORD_POLICY', 'MAX_LENGTH', '20', '최대 비밀번호 길이', '1', TIMESTAMP '2025-02-14 09:56:25', null, TIMESTAMP '2025-02-19 09:21:09', 'joo717@giens.co.kr');
INSERT INTO SITE_CONFIG (CONFIG_GROUP_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, USE_YN, SYSTEM_CREATE_DATE, SYSTEM_CREATE_USERID, SYSTEM_UPDATE_DATE, SYSTEM_UPDATE_USERID) VALUES ('PASSWORD_POLICY', 'REQUIRE_UPPERCASE', '1', '대문자 필수', '1', TIMESTAMP '2025-02-14 09:56:25', null, TIMESTAMP '2025-02-19 09:36:01', 'joo717@giens.co.kr');
INSERT INTO SITE_CONFIG (CONFIG_GROUP_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, USE_YN, SYSTEM_CREATE_DATE, SYSTEM_CREATE_USERID, SYSTEM_UPDATE_DATE, SYSTEM_UPDATE_USERID) VALUES ('PASSWORD_POLICY', 'REQUIRE_LOWERCASE', '1', '소문자 필수', '1', TIMESTAMP '2025-02-14 09:56:25', null, TIMESTAMP '2025-02-19 09:36:06', 'joo717@giens.co.kr');
INSERT INTO SITE_CONFIG (CONFIG_GROUP_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, USE_YN, SYSTEM_CREATE_DATE, SYSTEM_CREATE_USERID, SYSTEM_UPDATE_DATE, SYSTEM_UPDATE_USERID) VALUES ('PASSWORD_POLICY', 'REQUIRE_NUMBER', '1', '숫자 필수', '1', TIMESTAMP '2025-02-14 09:56:25', null, TIMESTAMP '2025-02-17 11:04:50', 'joo717@giens.co.kr');
INSERT INTO SITE_CONFIG (CONFIG_GROUP_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, USE_YN, SYSTEM_CREATE_DATE, SYSTEM_CREATE_USERID, SYSTEM_UPDATE_DATE, SYSTEM_UPDATE_USERID) VALUES ('PASSWORD_POLICY', 'REQUIRE_SPECIAL_CHARACTER', '1', '특수 문자 필수', '1', TIMESTAMP '2025-02-14 09:56:25', null, TIMESTAMP '2025-02-19 15:39:50', 'joo717@giens.co.kr');
INSERT INTO SITE_CONFIG (CONFIG_GROUP_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, USE_YN, SYSTEM_CREATE_DATE, SYSTEM_CREATE_USERID, SYSTEM_UPDATE_DATE, SYSTEM_UPDATE_USERID) VALUES ('WEB_SETTINGS', 'COMMENT', '개발자코멘트입니다', '프로젝트를 실행한 순간 모든 설정코드들을 불러와서 셋팅하는 것도 좋은 방법일것같습니다.', '0', TIMESTAMP '2025-03-05 10:58:49', 'joo717@giens.co.kr', TIMESTAMP '2025-03-05 10:59:17', 'joo717@giens.co.kr');
